title: record
email: 
description: REC Final Reprot
baseurl: "/record"
url: "http://shuhei555.github.io" # the base hostname & protocol for your si                      
github_username:  shuhei555
markdown: kramdown
lang: ja-JP                                                                     
#minimal_mistakes_skin: dark                                                                        
theme: jekyll-theme-cayman
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-org

permalink: /:categories/:short_year-:month-:day/:title

sass:
sass_dir: _sass
style: compressed

github: [metadata]
#lsi: true                                                                                          
# exclude:                                                                                         
#   - Gemfile                                                                                      
#   - Gemfile.lock                                                                                 
#   - node_modules                                                                                 
#   - vendor/bundle/                                                                               
#   - vendor/cache/                                                                                
#   - vendor/gems/                                                                                 
#   - vendor/ruby/  

